nathantannar4/InputBarAccessoryView

- InputBarAccessoryView/Views/InputBarAccessoryView.swift
I have altered the comments to make it clear how to set the max height yourself and that it is set automatically when `shouldAutoUpdateMaxTextViewHeight` is true.
> Improved comments when setting the max text view height

- InputBarAccessoryView/Plugins/AutocompleteManager/Views/AutocompleteCell.swift
layoutSubviews() should not be called directly.  This was causing issues with autocomplete images resizing when an image inset was used.
> Remove Call to layoutSubviews()

- CHANGELOG.md
- InputBarAccessoryView.xcodeproj/project.pbxproj
- InputBarAccessoryView/Models/HorizontalEdgeInsets.swift
* Renames `HorizontalEdgeInsets.swift.swift` to `HorizontalEdgeInsets.swift`
* Exposes the initializer and `zero` property of `HorizontalEdgeInsets`
**Justification per the Swift manual:**
> Default Memberwise Initializers for Structure Types
> The default memberwise initializer for a structure type is considered private if any of the structure’s stored properties are private. Likewise, if any of the structure’s stored properties are file private, the initializer is file private. **Otherwise, the initializer has an access level of internal**.
> 
> As with the default initializer above, if you want a public structure type to be initializable with a memberwise initializer when used in another module, you must provide a public memberwise initializer yourself as part of the type’s definition. …
> Fixes accessibility of HorizontalEdgePadding initializers and a typo in its filename

- Sources/InputBarAccessoryView.swift
- Sources/Views/SeparatorLine.swift
For #83 and #88. Also I don't have issue with #80 anymore, fwiw.
> Set separator line to 1px and update colors for iOS 13

- Sources/Plugins/AutocompleteManager/AutocompleteManager.swift
There are two separate cases this covers
1. make edits at the very start of a string when it starts with a tag without breaking the link
- This means a space before "@Nathan Tannar" will result in " @Nathan Tanner" without breaking the link.
2. make edits immediately before an inline tag without it breaking the link
- This means any input (for ex "Sup") before the tag in "Hey@Nathan Tannar" will result in "HeySup@Nathan Tanner" without breaking the link.
> Allow edits immediately before a tag without breaking them

- Sources/Extensions/UITextView+Extensions.swift
Fixes #108 
I don't think this actually fixes the root of the problem (`find(prefix:delimiterSet:)` seems to return matches with spaces even when delimiterSet is empty or when `maxSpaceCountDuringCompletion` is 0), but it's a working workaround for now.
> Fixes a bug where autocomplete would fail after using different prefixes

- Sources/Plugins/AttachmentManager/Views/AttachmentCell.swift
- Sources/Plugins/AttachmentManager/Views/ImageAttachmentCell.swift
Needed as custom `AttachmentCell`’s have to be dequeued to prevent crashes.
```swift
manager.attachmentView.dequeueReusableCell(withReuseIdentifier: AttachmentCell.reuseIdentifier, for: IndexPath(item: index, section: 0))
```
> Make reuseIdentifier public

- .gitignore
- Package.resolved
- Package.swift
- Updates SPM by adding package.resolved file here
- Updates RxSwift support to latest supporting Catalyst
- Updates gitignore file
This should be merged in and ideally released as version 4.3.3.
As discussed in https://github.com/nathantannar4/InputBarAccessoryView/pull/117 - we would then drop iOS 9, iOS 10, RxSwift (temporarily) and release version 5.0.0.
Current release 4.3.2 doesn't support SPM btw, users need to use master.
@nathantannar4 Let me know if you think we could proceed by merging this + other PRs as 4.3.3 and then proceed with the drop and prepare stuff for release 5.0.0.
> [Release 4.3.3] Update RxSwift, update Swift PM support

- Sources/Views/InputTextView.swift
Code would never reach plugins' `handleInput(of:)`.
> Fix image pasting logic in text field

- Sources/InputBarAccessoryView.swift
When I was doing unit testing on the items, the items wouldn't be set right away if I set animated to true, so the stack items property was empty until my animations were done.
> Add documentation for setStackViewItems

- CHANGELOG.md
- InputBarAccessoryView.podspec
- InputBarAccessoryView.xcodeproj/project.pbxproj
- README.md
Bump podspec, bump project version, update readme and changelog
- Drop support for iOS 9 and iOS 10 #117
- Remove `RxSwift`/`RxCocoa`  from SPM #128
- Fix image paste logic #126
- Fixed Getting started preview and hashtag typo #93
- Update documentation for setStackViewItems #82
> [5.0.0] Prepare release

- Sources/Extensions/UITextView+Extensions.swift
I'm building my own AutocompleteManager, and I'd like to re-use these functions instead of re-writing them in my target
> Update UITextView+Extensions to be public

- Sources/Plugins/AttachmentManager/Views/AttachmentCell.swift
- Sources/Plugins/AttachmentManager/Views/ImageAttachmentCell.swift
**Plugins/AttachmentManager**
Uses **open** instead of **public** for the **reuseIdentifier** properties in **AttachmentCell** and **ImageAttachmentCell**.
As a result these classes are suitable for inheritance.
#145 
**Devices/Simulators:** iPhone X / Simulator iPhone 11 Pro
**iOS Version:** 13.5 / 14.0
**Swift Version:** 5
**InputBarAccessoryView Version:** 5.2.1
> AttachmentCell - open reuseIdentifier

- Sources/Controls/InputBarSendButton.swift
- When using dark mode, the loading indicator that can be displayed on the send button was not visible because it was not using the updated styles available in iOS 13+.
Before & After
**Devices/Simulators:** iPhone 8, iPhone 12
**iOS Version:** iOS 12 and 13
**Swift Version:** Swift 5
**InputBarAccessoryView Version:** Latest
> Add dark mode support for loading indicator on send button

- Sources/Views/InputTextView.swift
Fixes #175 
#175 
Can no longer directly access pasteboard without the system notifying the user 
**Devices/Simulators:** XS Max
**iOS Version:** iOS 14.1
**Swift Version:** 5.3
**InputBarAccessoryView Version:** 5.2.0
> Fix for iOS 14 paste notification

- Example/Example/SubviewExampleViewController.swift
- Sources/Views/InputTextView.swift
I was working on implementing this, and using the example app as a playground was the easiest way to prototype
> InputTextView: allow setting of canBecomeFirstResponder + add example

- CHANGELOG.md
- Sources/KeyboardManager/KeyboardManager.swift
This PR addresses the issue linked below. 
- Allowed additional bottom space to be applied to the interactive keyboard dismissal
- Added a flag to determine if the additional bottom space should also be applied
Closes #198 
**Devices/Simulators:** Simulators
**iOS Version:** 14.4
**Swift Version:** 5
**InputBarAccessoryView Version:** 5.3.0
> Apply additionalBottomSpace to interactive dismissal

- Sources/Plugins/AutocompleteManager/AutocompleteManager.swift
Provides dark mode support for auto-completion in `AutoCompleteManger`.
Closes #205 
No
No
**Devices/Simulators:** Device
**iOS Version:** 14.4.2
**Swift Version:** Swift 5
**InputBarAccessoryView Version:** 5.1.0
> AutoComplete attributed text dark mode support add

- CHANGELOG.md
- Sources/KeyboardManager/KeyboardManager.swift
This fix resets the cached notification that contains the keyboard start and end frames when the keyboard is hidden. The cached notification keeps track of the last position of the keyboard so that the pan gesture can correctly calculate the position of the input bar (see KeyboardManager.handlePanGestureRecognizer()).
There is an issue within the handlePanGestureRecognizer() algorithm when the keyboard gets dismissed programmatically. The cached notification contains the incorrect frames when it solely relies on being set from the willChangeFrame and didChangeFrame notifications. We expect the startFrame and endFrame of the notification to be the same, but they are not. 
This code …
> KeyboardManager reset cachedNotification onHide

- Sources/KeyboardManager/KeyboardManager.swift
Fix compilation on Xcode 13.
https://github.com/nathantannar4/InputBarAccessoryView/issues/213
No.
**Devices/Simulators:** iPhone 12 Pro
**iOS Version:** iOS 15 Beta 4
**Swift Version:** Swift 5.5
**InputBarAccessoryView Version:** master branch
> Mark KeyboardManager unavailable in extension

- Sources/Plugins/AttachmentManager/AttachmentManager.swift
- Sources/Plugins/AttachmentManager/Protocols/AttachmentManagerDataSource.swift
This implements a simple (optional) AttachmentManagerDataSource method to allow for custom attachment sizes.
For my own app, I found this functionality very needed and it has been tested continuously throughout my app's development with no issues. 
Not to my knowledge, based on what I have seen/
This feature could be seen as niche but when it is needed, it is very helpful.
**Devices/Simulators:** iPhoneXR, iPhone11, iPhone12, (+Max …
> Custom Attachment Size

- Sources/InputBarAccessoryView.swift
When adjusting the left and right stack view width constraints, while I liked having them animated, I felt like there needed to be a way to run other animations concurrently. 
One example would be changing the alpha component of the stack view items as they are compressed so they don't appear small in the end. 
Because of this, I added a simple optional closure which, if specified, is called while animating to also animate the given properties. 
Not that I am aware of.
The name of the …
> Added extra animations option for left/right stack view constraints

- CHANGELOG.md
- Sources/KeyboardManager/KeyboardManager.swift
- KeyboardManager would update position of inputAccessoryView even when the keyboard was undocked and floating
…
…
**Devices/Simulators:** …
**iOS Version:** …
**Swift Version:** …
**InputBarAccessoryView Version:** …
> inputAccessoryView position with floating keyboard

- CHANGELOG.md
- README.md
- docs/index.html
Nothing changed in the code, it’s just a typo fix (it’s `Xcode`, not `XCode`).
I don’t think so.
None.
None.
**Devices/Simulators:** N/A
**iOS Version:** N/A
**Swift Version:** N/A
**InputBarAccessoryView Version:** N/A
> Fix Xcode case in the project

- CHANGELOG.md
- Sources/KeyboardManager/KeyboardManager.swift
This fixes layout (gap) issues when keyboard appears on iPad when VC is presented as pagesheet of formsheet.
Closes #238
none
The fixes are a bit hacky but it's the only way I could find that works.
**Devices/Simulators:** 
iPad with and without home button, landscape and portrait (important). Also tested on various iPhones to make sure it kept working fine there too.
**iOS Version:** 
14/15/16
**Swift Version:** 
the one used by …
> Fix layout issues on iPad pagesheets

- Sources/Plugins/AttachmentManager/AttachmentManager.swift
Fixes Issue #237 by returning the default cell size if the attachment cell is shown and the indexPath is set to the attachment cell.
No
Error reported when the example app crashes:
Swift/ContiguousArrayBuffer.swift:600: Fatal error: Index out of range
**Devices/Simulators:** 
iPhone 14 Pro simulator
**iOS Version:** 
iOs 16.4
**Swift Version:** 
5.7
**InputBarAccessoryView Version:** 
6.2.0
> bug: Fixed library crash after adding image attachment #237

- .github/workflows/ci_master_framework.yml
- .github/workflows/ci_pr_example.yml
- .github/workflows/ci_pr_framework.yml
- GitHubActions/build.sh
- Package.swift
- Sources/KeyboardManager/KeyboardManager.swift
- Sources/Plugins/AttachmentManager/Views/AttachmentCell.swift
- the bottom gap had incorrect calculation for iPads when controller is not starting at y: 0. This should fix it.
- Closes: https://github.com/nathantannar4/InputBarAccessoryView/issues/141
> Fix bottom gap calculations for embedded controllers

- Sources/InputBarAccessoryView.swift
This fixes #264
I'm not sure if it's a proper fix for the library, but it works good in my case.
I believe the code above the fix is still needed to manage `inputTextView.isScrollEnabled` state with the height constraint, so it shouldn't be placed in `else` statement.
https://github.com/nathantannar4/InputBarAccessoryView/blob/093bdc71dc26bfcdaa71352d5ff0cd84b9b8d427/Sources/InputBarAccessoryView.swift#L571-L586
> Consider custom middleContentView height

- Sources/InputBarAccessoryView.swift
I'll need to find a different fix for the main thread issue, but wrapping the whole `performLayout` call in dispatch main async can have some unintended consequences. This function is called in a bunch of places and because the async call is.. async, it essentially delays the completion block even when `animate: false` and thus callers that expect the block to be executed right away may get the wrong result.
> Don't do performLayout async after all

- .github/workflows/ci_master_framework.yml
- .github/workflows/ci_pr_example.yml
- .github/workflows/ci_pr_framework.yml
- CHANGELOG.md
- Example/Example.xcodeproj/project.pbxproj
- Example/Sources/Example ViewControllers/AdditionalBottomSpaceExampleViewController.swift
- GitHubActions/build.sh
- Package.swift
- README.md
- Sources/Models/HorizontalEdgePadding.swift
- Sources/Models/NSConstraintLayoutSet.swift
- Sources/Plugins/AttachmentManager/AttachmentManager.swift
- Sources/Plugins/AutocompleteManager/Protocols/AutocompleteManagerDataSource.swift
- Sources/Protocols/InputBarAccessoryViewDelegate.swift
- Sources/Protocols/InputItem.swift
- Sources/Protocols/InputPlugin.swift
- Migrate to Swift 6
- Fully enable Swift concurrency
- Drop iOS 13 - even tho Swift concurrency has been backed-in for iOS 13, it's recommended to use iOS 14+, so I don't see a reason why keeping it around - those users should stick to 6.5.0 release
- Update example project
Fixes https://github.com/nathantannar4/InputBarAccessoryView/issues/273
> Migrate to Swift 6, fully support async/await and Swift concurrency, drop iOS 13
